name: SmartClipboard
targets:
  SmartClipboard:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: SmartClipboard
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.saihgupr.SmartClipboard
      INFOPLIST_FILE: Info.plist
      GENERATE_INFOPLIST_FILE: NO
      CODE_SIGNING_ALLOWED: YES
      CODE_SIGNING_STYLE: Manual
      CODE_SIGN_IDENTITY: "Apple Development"
      CODE_SIGN_ENTITLEMENTS: SmartClipboard/SmartClipboard.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      MARKETING_VERSION: 1.0.2
