blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/saihgupr/SmartClipboard/discussions
    about: Please ask questions or search for answers in our Discussions tab.
