import AppKit
import Combine
import SwiftData
import SwiftUI

@Model
final class ClipboardItem: Identifiable {
    @Attribute(.unique) var id: UUID
    var content: String
    var timestamp: Date
    var isIncognito: Bool = false
    var isPinned: Bool = false
    var isFavorite: Bool = false
    
    init(id: UUID = UUID(), content: String, timestamp: Date = Date(), isIncognito: Bool = false, isPinned: Bool = false, isFavorite: Bool = false) {
        self.id = id
        self.content = content
        self.timestamp = timestamp
        self.isIncognito = isIncognito
        self.isPinned = isPinned
        self.isFavorite = isFavorite
    }
}

@MainActor
class ClipboardManager: ObservableObject {
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int = 0
    private var timer: Timer?
    private let modelContext: ModelContext
    private var isPastingSequentially = false
    
    /// Optional callback invoked when a paste operation is triggered from the UI.
    var onPaste: (() -> Void)?

    /// Tracks if the app has macOS Accessibility permissions required for simulated keystrokes (Cmd+V).
    @Published var hasAccessibilityPermission: Bool = AXIsProcessTrusted()
    
    /// The currently visible/displayed clipboard items in the UI.
    @Published var visibleItems: [ClipboardItem] = []
    
    @Published var incognitoMode: Bool = UserDefaults.standard.bool(forKey: "incognitoMode") {
        didSet {
            UserDefaults.standard.set(incognitoMode, forKey: "incognitoMode")
            if !incognitoMode {
                clearIncognitoItems()
            }
        }
    }

    init(modelContext: ModelContext) {
        self.modelContext = modelContext
        lastChangeCount = pasteboard.changeCount
        startPolling()

        // Run an initial pruning of old records
        pruneOldRecords()

        // Install global hotkeys (Cmd+N and Option+N) that work from any app
        GlobalHotkeyManager.shared.onPasteItem = { [weak self] index in
            self?.pasteItem(at: index)
        }
        GlobalHotkeyManager.shared.onPasteMultiple = { [weak self] count in
            self?.pasteMultiple(count: count)
        }
        GlobalHotkeyManager.shared.install()

        // Check permissions immediately; auto-prompt if missing
        refreshAccessibilityPermission()
        if !hasAccessibilityPermission {
            requestAccessibilityPermission()
        }
    }

    func startPolling() {
        // Check the clipboard and accessibility permissions every 1 second
        timer = Timer.scheduledTimer(withTimeInterval: 1.0, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.checkForChanges()
                
                // If we don't have permission, keep checking so the warning can disappear automatically
                if self?.hasAccessibilityPermission == false {
                    self?.refreshAccessibilityPermission()
                }
            }
        }
    }

    func refreshAccessibilityPermission() {
        let trusted = AXIsProcessTrusted()
        if hasAccessibilityPermission != trusted {
            hasAccessibilityPermission = trusted
        }
    }

    /// Triggers the macOS system prompt to request Accessibility permissions.
    func requestAccessibilityPermission() {
        let options = [kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String: true]
        AXIsProcessTrustedWithOptions(options as CFDictionary)
        refreshAccessibilityPermission()
    }

    func checkForChanges() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // Security: Prevent saving sensitive clipboard items (e.g. from password managers)
        let types = pasteboard.types ?? []
        let sensitiveTypes: [NSPasteboard.PasteboardType] = [
            .init("org.nspasteboard.TransientType"),
            .init("org.nspasteboard.ConcealedType"),
            .init("com.agilebits.onepassword"),
            .init("org.nspasteboard.AutoGeneratedType"),
            .init("com.apple.uikit.pasteboard.concealed")
        ]

        for sensitiveType in sensitiveTypes {
            if types.contains(sensitiveType) {
                print("Ignored sensitive clipboard item of type: \(sensitiveType.rawValue)")
                return
            }
        }

        // Defense-in-depth: heuristic check for undocumented or newer sensitive types
        for type in types {
            let typeString = type.rawValue.lowercased()
            if typeString.contains("password") || typeString.contains("concealed") || typeString.contains("transient") || typeString.contains("secret") {
                print("Ignored sensitive clipboard item via heuristic match: \(type.rawValue)")
                return
            }
        }

        if let newString = pasteboard.string(forType: .string), !newString.isEmpty {
            // Enforce length limit to prevent memory exhaustion / DoS
            let truncatedString = String(newString.prefix(100_000))

            // Check for any existing item with the same content to implement "move-to-top"
            let predicate = #Predicate<ClipboardItem> { $0.content == truncatedString }
            var descriptor = FetchDescriptor<ClipboardItem>(predicate: predicate)
            descriptor.fetchLimit = 1
            
            do {
                let existingItems = try modelContext.fetch(descriptor)
                
                if let existingItem = existingItems.first {
                    // Item already exists - just update its timestamp to move it to top
                    existingItem.timestamp = Date()
                    // If we are in incognito mode, mark it so it gets deleted later
                    if UserDefaults.standard.bool(forKey: "incognitoMode") {
                        existingItem.isIncognito = true
                    }
                } else {
                    // New unique item - insert it
                    let modeOn = UserDefaults.standard.bool(forKey: "incognitoMode")
                    let item = ClipboardItem(content: truncatedString, isIncognito: modeOn)
                    modelContext.insert(item)
                }
                
                try modelContext.save()
                
                // Periodically prune old records based on retention settings
                pruneOldRecords()
            } catch {
                print("Failed to handle new clipboard item: \(error)")
            }
        }
    }
    
    func delete(item: ClipboardItem) {
        modelContext.delete(item)
        try? modelContext.save()
    }
    
    func togglePin(item: ClipboardItem) {
        item.isPinned.toggle()
        try? modelContext.save()
    }
    
    func toggleFavorite(item: ClipboardItem) {
        item.isFavorite.toggle()
        try? modelContext.save()
    }
    
    @AppStorage("historyRetentionDays") private var historyRetentionDays: Int = 180
    
    func clearIncognitoItems() {
        let predicate = #Predicate<ClipboardItem> { $0.isIncognito }
        let descriptor = FetchDescriptor<ClipboardItem>(predicate: predicate)
        do {
            let items = try modelContext.fetch(descriptor)
            for item in items {
                modelContext.delete(item)
            }
            try modelContext.save()
        } catch {
            print("Failed to clear incognito items: \(error)")
        }
    }
    
    /// Deletes all items from history for a clean start.
    func clearAllHistory() {
        do {
            try modelContext.delete(model: ClipboardItem.self)
            try modelContext.save()
            // Reset tracking so we don't immediately re-save the current system clipboard
            lastChangeCount = pasteboard.changeCount
        } catch {
            print("Failed to clear all history: \(error)")
        }
    }
    
    /// Deletes items older than the threshold set in settings
    private func pruneOldRecords() {
        guard historyRetentionDays > 0 else { return } // 0 means "Forever"
        
        let retentionDays = historyRetentionDays
        let cutoff = Calendar.current.date(byAdding: .day, value: -retentionDays, to: Date())!
        
        do {
            try modelContext.delete(model: ClipboardItem.self, where: #Predicate { item in
                item.timestamp < cutoff && !item.isPinned && !item.isFavorite
            })
            try modelContext.save()
        } catch {
            print("Failed to prune old records: \(error)")
        }
    }
    
    func recordContentInDatabase(content: String) {
        guard !content.isEmpty else { return }
        let truncatedString = String(content.prefix(100_000))
        
        let predicate = #Predicate<ClipboardItem> { $0.content == truncatedString }
        var descriptor = FetchDescriptor<ClipboardItem>(predicate: predicate)
        descriptor.fetchLimit = 1
        
        do {
            let existingItems = try modelContext.fetch(descriptor)
            
            if let existingItem = existingItems.first {
                existingItem.timestamp = Date()
                if UserDefaults.standard.bool(forKey: "incognitoMode") {
                    existingItem.isIncognito = true
                }
            } else {
                let modeOn = UserDefaults.standard.bool(forKey: "incognitoMode")
                let item = ClipboardItem(content: truncatedString, isIncognito: modeOn)
                modelContext.insert(item)
            }
            
            try modelContext.save()
            pruneOldRecords()
        } catch {
            print("Failed to record pasted/copied content: \(error)")
        }
    }
    
    func copyToClipboard(item: ClipboardItem) {
        // Move to top when explicitly copying via Quick Copy or similar
        item.timestamp = Date()
        try? modelContext.save()
        copyToClipboard(content: item.content, recordInDatabase: false)
    }

    func copyToClipboard(content: String, recordInDatabase: Bool = false) {
        if recordInDatabase {
            recordContentInDatabase(content: content)
        }
        
        pasteboard.clearContents()
        pasteboard.setString(content, forType: .string)
        // Update change count so we don't re-save what we just copied
        lastChangeCount = pasteboard.changeCount 
    }

    @AppStorage("shiftEnterApps") private var shiftEnterAppsJSON: String = "[]"
    
    private var shiftEnterBundleIDs: [String] {
        guard let data = shiftEnterAppsJSON.data(using: .utf8) else { return [] }
        return (try? JSONDecoder().decode([String].self, from: data)) ?? []
    }

    func paste(item: ClipboardItem, isGlobalHotkey: Bool = false) {
        // Move to top by updating timestamp
        item.timestamp = Date()
        try? modelContext.save()
        
        paste(content: item.content, isGlobalHotkey: isGlobalHotkey)
    }

    func paste(content: String, isGlobalHotkey: Bool = false) {
        copyToClipboard(content: content)

        // Always trigger the callback if someone is listening.
        // StatusItemManager uses this to close the popover.
        onPaste?()

        // If SmartClipboard's window is frontmost, hide it so focus returns to the
        // previous app. When triggered via global hotkey the app is already in the
        // background, so we skip the hide.
        let needsHide = !isGlobalHotkey && NSApp.isActive
        
        if needsHide {
            NSApp.hide(nil)
        }

        // Perform the paste with a delay to allow focus to settle back to the target app.
        let delay: Double = needsHide ? 0.25 : 0.05
        DispatchQueue.main.asyncAfter(deadline: .now() + delay) {
            self.simulatePaste()
        }
    }

    private func simulatePaste() {
        let source = CGEventSource(stateID: .combinedSessionState)
        
        // Disable local keyboard events while pasting to prevent interference
        source?.setLocalEventsFilterDuringSuppressionState([.permitLocalMouseEvents, .permitSystemDefinedEvents],
                                                           state: .eventSuppressionStateSuppressionInterval)

        // Add flag that left/right modifier key has been pressed
        let cmdFlag = CGEventFlags(rawValue: UInt64(NSEvent.ModifierFlags.command.rawValue) | 0x000008)
        let vCode: CGKeyCode = 0x09 // kVK_ANSI_V
        
        let keyVDown = CGEvent(keyboardEventSource: source, virtualKey: vCode, keyDown: true)
        let keyVUp = CGEvent(keyboardEventSource: source, virtualKey: vCode, keyDown: false)
        
        keyVDown?.flags = cmdFlag
        keyVUp?.flags = cmdFlag
        
        // Post down event
        keyVDown?.post(tap: .cgSessionEventTap)
        
        // ⚡ Bolt: Add small gap between down and up for app event loops to process correctly
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.01) {
            keyVUp?.post(tap: .cgSessionEventTap)
        }
    }

    // MARK: - Global hotkey handlers

    /// Fetches the item at the given 0-based index (pinned first, newest-first) and pastes it.
    func pasteItem(at index: Int) {
        let isUIVisible = (NSApp.windows.first(where: { $0.className.contains("KeyPanel") })?.isVisible ?? false) || NSApp.isActive
        
        let items: [ClipboardItem]
        if isUIVisible, !visibleItems.isEmpty {
            items = visibleItems
        } else {
            var descriptor = FetchDescriptor<ClipboardItem>(
                sortBy: [SortDescriptor(\ClipboardItem.timestamp, order: .reverse)]
            )
            guard let allItems = try? modelContext.fetch(descriptor) else { return }
            let pinned = allItems.filter { $0.isPinned }
            let unpinned = allItems.filter { !$0.isPinned }
            items = pinned + unpinned
        }
        guard index < items.count else { return }
        paste(item: items[index], isGlobalHotkey: !isUIVisible)
    }

    /// Fetches the most-recent `count` items and pastes them oldest→newest.
    func pasteMultiple(count: Int) {
        guard !isPastingSequentially else {
            print("[ClipboardManager] Already pasting sequentially, ignoring request.")
            return
        }
        
        let isUIVisible = (NSApp.windows.first(where: { $0.className.contains("KeyPanel") })?.isVisible ?? false) || NSApp.isActive
        
        let items: [ClipboardItem]
        if isUIVisible, !visibleItems.isEmpty {
            items = visibleItems
        } else {
            var descriptor = FetchDescriptor<ClipboardItem>(
                sortBy: [SortDescriptor(\ClipboardItem.timestamp, order: .reverse)]
            )
            guard let allItems = try? modelContext.fetch(descriptor) else { return }
            let pinned = allItems.filter { $0.isPinned }
            let unpinned = allItems.filter { !$0.isPinned }
            items = pinned + unpinned
        }
        guard !items.isEmpty else { return }
        
        let targetItems = Array(items.prefix(count).reversed())
        
        if isUIVisible {
            isPastingSequentially = true
            onPaste?()
            if NSApp.isActive {
                NSApp.hide(nil)
            }
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.25) { [weak self] in
                self?.pasteSequentially(targetItems)
            }
        } else {
            isPastingSequentially = true
            pasteSequentially(targetItems)
        }
    }

    private func pasteSequentially(_ items: [ClipboardItem], index: Int = 0) {
        guard index < items.count else {
            isPastingSequentially = false
            return
        }
        
        // Update clipboard content
        copyToClipboard(content: items[index].content)
        
        // Simulate paste (Cmd+V)
        simulatePaste()
        
        // Determine the next step delay
        if index < items.count - 1 {
            // If there are more items, send an Enter/Shift+Enter to separate them
            // Increased delay to 0.40s to ensure the paste has finished processing in the target app
            let separatorDelay: Double = 0.40
            DispatchQueue.main.asyncAfter(deadline: .now() + separatorDelay) {
                let source = CGEventSource(stateID: .combinedSessionState)
                source?.setLocalEventsFilterDuringSuppressionState([.permitLocalMouseEvents, .permitSystemDefinedEvents],
                                                                   state: .eventSuppressionStateSuppressionInterval)
                
                // Determine if we need Shift+Enter vs Enter
                let activeApp = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
                let useShift = activeApp != nil && self.shiftEnterBundleIDs.contains(activeApp!)
                
                let kVK_Return: CGKeyCode = 0x24
                
                let retd = CGEvent(keyboardEventSource: source, virtualKey: kVK_Return, keyDown: true)
                let retu = CGEvent(keyboardEventSource: source, virtualKey: kVK_Return, keyDown: false)
                
                if useShift {
                    let shiftFlag = CGEventFlags(rawValue: UInt64(NSEvent.ModifierFlags.shift.rawValue) | 0x000002)
                    retd?.flags = shiftFlag
                    retu?.flags = shiftFlag
                } else {
                    // Explicitly clear flags to prevent physical keys (like Option) from interfering
                    retd?.flags = CGEventFlags()
                    retu?.flags = CGEventFlags()
                }
                
                retd?.post(tap: .cgSessionEventTap)
                // Small gap before Enter up
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.01) {
                    retu?.post(tap: .cgSessionEventTap)
                    
                    // After Enter is finished, trigger the next paste with a safe margin
                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.40) { [weak self] in
                        self?.pasteSequentially(items, index: index + 1)
                    }
                }
            }
        } else {
            // Last item pasted, reset flag
            isPastingSequentially = false
        }
    }
}
